C++ 20 Fix | UE5.3
grpht/TCPClientPlugin pull request #1
Opened 2023-09-20 12:24 UTC by yexiuph

There's an error for /std:c++20

[Error]C4855 implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'

Fixing the plugin to
 ThrdPool->EnqueueJob([=, this]()

2023-09-20 15:47 UTC, grpht requested changes
It has the following error in the other version.
"Error C3791 'this' cannot be explicitly captured when the default capture mode is by copy (=)"
How about getting a member variable through 'this' and capturing the other variable directly?

2023-09-20 15:47 UTC, grpht commented on Source/TCPClientPlugin/Private/TCPClient.cpp
> +    ThrdPool->EnqueueJob([=, this]()
```
ThrdPool->EnqueueJob([this, RemoteAddress, state, connectCallback]()
```

2023-09-20 15:47 UTC, grpht commented on Source/TCPClientPlugin/Private/TCPClient.cpp
> +    ThrdPool->EnqueueJob([=, this]()
```
ThrdPool->EnqueueJob([this, state, callback]()
```

2023-09-20 15:47 UTC, grpht commented on Source/TCPClientPlugin/Private/TCPClient.cpp
> +    ThrdPool->EnqueueJob([=, this]()
```
ThrdPool->EnqueueJob([this, buffer, bufferSize, state, callback]()
```

2023-09-21 06:56 UTC, yexiuph commented
Added the requested changes. Thank you.

2023-09-21 17:13 UTC, merged

2023-09-21 17:15 UTC, grpht commented
Thank you for your contribution, yexiuph!